---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: "3-jdk-8-slim"

inputs:
- name: code

outputs:
- name: package-output

run:
  path: code/ci/tasks/package.sh

