apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  ports:
  - port: 8080 # expose this service on port 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-demo