---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: code
  type: git
  source:
    uri: https://github.com/benwilcock/pcf-springboot-demo
    branch: master

- name: push-to-pcf
  type: cf
  source:
    api: {{cf-endpoint}}
    username: {{cf-user}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: true

- name: timer
  type: time
  source: {interval: 24h}

- name: slack-alert
  type: slack-notification
  source:
    url: {{webhook}}
    insecure: true

jobs:
- name: unit-test
  public: true
  plan:
  - get: code
    trigger: true
  - get: timer
    trigger: true
  - task: test
    file: code/ci/tasks/unit-test.yml

- name: push-connected
  public: true
  plan:
  - get: code
    trigger: true
    passed: [unit-test]
  - get: timer
    trigger: true
    passed: [unit-test]
  - task: package
    file: code/ci/tasks/package.yml
  - put: push-to-pcf
    params:
      manifest: code/manifest-connected.yml
      path: package-output/pcf-springboot-demo.jar

- name: push-disconnected
  public: true
  plan:
  - get: code
    trigger: true
    passed: [unit-test]
  - get: timer
    trigger: true
    passed: [unit-test]
  - task: package
    file: code/ci/tasks/package.yml
  - put: push-to-pcf
    params:
      manifest: code/manifest-disconnected.yml
      path: package-output/pcf-springboot-demo.jar

- name: test-connected
  public: true
  plan:
  - get: code
    trigger: true
    passed: [push-connected]
  - get: timer
    trigger: true
    passed: [push-connected]
  - task: test-disconnected
    file: code/ci/tasks/web-test-connected.yml
    params:
      URL: http://pcf-springboot-demo-connected.cfapps.io
  - put: slack-alert
    params:
      text: |
        The web test for $BUILD_PIPELINE_NAME.$BUILD_JOB_NAME has passed!

- name: test-disconnected
  public: true
  plan:
  - get: code
    trigger: true
    passed: [push-disconnected]
  - get: timer
    trigger: true
    passed: [push-disconnected]
  - task: test-disconnected
    file: code/ci/tasks/web-test-disconnected.yml
    params:
      URL: http://pcf-springboot-demo-disconnected.cfapps.io
  - put: slack-alert
    params:
      text: |
        The web test for $BUILD_PIPELINE_NAME.$BUILD_JOB_NAME has passed!
